### ISSUE TITLE
Controls page not loading on certain browsers.

### ISSUE THREAD

**Issue by 13bfc3s** [barkermn01/TwitchPlaySnes#1]
After logging in, the webpage shows a spinning loading icon and does not progress on chrome and edge, but works correctly on firefox.
Tested on 2 computers (windows 7, windows 10) and 3 browsers (firefox v71, chrome v79, edge 44.18362)

**Comment by barkermn01** [comment]
@sirpipthegreat thanks for the report could you tell me what version of Chrome & Edge your working on and if there are any console errors in the web inspector, please?

It's strange as I built the system using Chrome.

**Comment by barkermn01** [comment]
There has been some updates and this working on another stream I'm unsure why it's not working for you and without a little more info I'm unable to help with this.
